app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("stations/", views.StationsView.as_view(), name="stations"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("save_favorite_route/", views.save_favorite_route, name="save_favorite_route"),
    path("stations/<int:station_id>/", views.station_detail, name="station_detail"),
    path("alerts/", views.alerts_view, name="alerts"),
]

messaging/urls.py
from django.urls import path
from . import views

app_name = "messaging"
urlpatterns = [
    path("inbox", views.inbox, name="inbox"),
    path(
        "direct_messaging/<str:messaging_partner_name>/",
        views.direct_messaging,
        name="direct_messaging",
    ),
    path(
        "send_message/<str:recipient_username>/",
        views.send_message,
        name="send_message",
    ),
    path(
        "get_new_messages/<str:messaging_partner_name>/",
        views.get_new_messages,
        name="get_new_messages",
    ),
    path(
        "block_user/<str:messaging_partner_name>/",
        views.block_user,
        name="block_user",
    ),
]

stepfreemta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("app/", include("app.urls", namespace="app")),
    path("admin/", admin.site.urls),
    path("admin_panel/", include("admin_panel.urls", namespace="admin_panel")),
    path("maps/", include("maps.urls", namespace="maps")),
    path("messaging/", include("messaging.urls", namespace="messaging")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
    path("reporting/", include("reporting.urls", namespace="reporting")),
    path("", lambda request: redirect("maps:map_view"), name="landing_page"),
]

messaging/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(
        User, related_name="sent_messages", on_delete=models.CASCADE
    )
    recipient = models.ForeignKey(
        User, related_name="received_messages", on_delete=models.CASCADE
    )
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.sender} to {self.recipient} at {self.timestamp}"


class BlockedUser(models.Model):
    blocker = models.ForeignKey(User, related_name="blocker", on_delete=models.CASCADE)
    blocked = models.ForeignKey(User, related_name="blocked", on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.blocker} blocked {self.blocked} at {self.timestamp}"

messaging/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["content"]


class UserSearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, label="Search Users")

messaging/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Message, BlockedUser
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.shortcuts import get_object_or_404
from .forms import UserSearchForm
from django.core.exceptions import PermissionDenied
from django.utils.html import escape


@login_required
def inbox(request):
    form = UserSearchForm(request.GET or None)
    requested_users = None
    users_searched = False
    if form.is_valid():
        query = form.cleaned_data.get("query")
        if query:
            requested_users = User.objects.filter(
                username__icontains=query
            ).values_list("username", flat=True)
            users_searched = True

    conversation_history = {}
    messages_history = Message.objects.filter(
        Q(sender=request.user) | Q(recipient=request.user)
    ).order_by("timestamp")

    blocked_users = BlockedUser.objects.filter(blocker=request.user).values_list(
        "blocked__username", flat=True
    )

    for message in messages_history:
        if message.sender.username == request.user.username:
            messaging_partner = message.recipient.username
        else:
            messaging_partner = message.sender.username
        if (users_searched and messaging_partner not in requested_users) or (
            messaging_partner in blocked_users
        ):
            continue
        conversation_history[messaging_partner] = {
            "sender": message.sender.username,
            "recipient": message.recipient.username,
            "content": escape(message.content),
            "timestamp": message.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
        }

    start_conversations = []
    if users_searched:
        for username in requested_users:
            if (
                username != request.user.username
                and username not in conversation_history
                and username not in blocked_users
            ):
                start_conversations.append(username)
    return render(
        request,
        "messaging/inbox.html",
        {
            "form": form,
            "conversation_history": conversation_history,
            "start_conversations": start_conversations,
        },
    )


@login_required
def direct_messaging(request, messaging_partner_name):
    messaging_partner = get_object_or_404(User, username=messaging_partner_name)
    if messaging_partner == request.user:
        raise PermissionDenied
    blocked_users = BlockedUser.objects.filter(blocker=request.user).values_list(
        "blocked__username", flat=True
    )
    if messaging_partner.username in blocked_users:
        raise PermissionDenied
    messages_history = Message.objects.filter(
        (Q(sender=request.user) & Q(recipient=messaging_partner))
        | Q(sender=messaging_partner) & Q(recipient=request.user)
    ).order_by("timestamp")
    messages_data = [
        {
            "sender": message.sender.username,
            "recipient": message.recipient.username,
            "content": escape(message.content),
            "timestamp": message.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
        }
        for message in messages_history
    ]
    return render(
        request,
        "messaging/direct_messaging.html",
        {"messages": messages_data, "messaging_partner": messaging_partner.username},
    )


@login_required
@csrf_exempt
def send_message(request, recipient_username):
    recipient = get_object_or_404(User, username=recipient_username)
    if recipient == request.user:
        raise PermissionDenied
    blocked_users = BlockedUser.objects.filter(blocker=request.user).values_list(
        "blocked__username", flat=True
    )
    if recipient.username in blocked_users:
        raise PermissionDenied
    if request.method == "POST":
        content = request.POST["content"]
        if content:
            Message.objects.create(
                sender=request.user, recipient=recipient, content=content
            )
            return JsonResponse({"status": "Message sent"})
    return render(request, "messaging/send_message.html", {"recipient": recipient})


@login_required
def get_new_messages(request, messaging_partner_name):
    messaging_partner = get_object_or_404(User, username=messaging_partner_name)
    if messaging_partner == request.user:
        raise PermissionDenied
    blocked_users = BlockedUser.objects.filter(blocker=request.user).values_list(
        "blocked__username", flat=True
    )
    if messaging_partner.username in blocked_users:
        raise PermissionDenied
    messages_history = Message.objects.filter(
        (Q(sender=request.user) & Q(recipient=messaging_partner))
        | Q(sender=messaging_partner) & Q(recipient=request.user)
    ).order_by("timestamp")
    messages_data = [
        {
            "sender": message.sender.username,
            "recipient": message.recipient.username,
            "content": escape(message.content),
            "timestamp": message.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
        }
        for message in messages_history
    ]
    return JsonResponse({"messages": messages_data})


@login_required
def block_user(request, messaging_partner_name):
    messaging_partner = get_object_or_404(User, username=messaging_partner_name)
    if messaging_partner == request.user:
        raise PermissionDenied
    already_blocked = BlockedUser.objects.filter(
        blocker=request.user, blocked=messaging_partner
    )
    if already_blocked:
        return redirect("messaging:inbox")

    BlockedUser.objects.create(blocker=request.user, blocked=messaging_partner)
    return redirect("messaging:inbox")

messaging/templates/messaging/direct_messaging.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'messaging/direct_messaging.css' %}">

    <title>Inbox</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function fetchMessages() {
            if(dialog.open){
                return
            }
            $.get("{% url 'messaging:get_new_messages' messaging_partner_name=messaging_partner%}", function (data) {
                let messagesContainer = $('#messages-container');
                messagesContainer.empty();
                data.messages.forEach(function (message) {
                    let className = message.sender === '{{ user.username }}' ? 'message-right' : 'message-left';
                    messagesContainer.append(
                        `<div class=${className}>
                            <p>
                                <strong>${message.sender}</strong> <br>
                                ${message.content} <br>
                                (${message.timestamp})
                            </p>
                        </div>`
                    );
                });
                if (messagesContainer.children().length === 0) {
                    messagesContainer.append(`<p>No messages to show.</p>`);
                }
            });

            document.get
        }

        $(document).ready(function () {
            fetchMessages();
            setInterval(fetchMessages, 1000); // Fetch messages every 1 seconds

            $('form').on('submit', function (e) {
                e.preventDefault();
                const content = $('textarea[name="content"]').val();
                if (content) {
                    $.ajax({
                        type: 'POST',
                        url: "{% url 'messaging:send_message' recipient_username=messaging_partner %}",
                        data: {
                            'content': content,
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        success: function (response) {
                            if (response.status === 'Message sent') {
                                $('textarea[name="content"]').val('');
                                fetchMessages();
                            }
                        }
                    });
                }
            });
        });
    </script>
    <style>
        .message-left {
            text-align: left;
        }

        .message-right {
            text-align: right;
        }
    </style>
</head>

<body>
    <a href="{% url 'messaging:inbox' %}"><button>Inbox</button></a>
    <div id="messages-container">
        {% for message in messages %}
        <div class="{% if message.sender == user.username %}
                        message-right
                    {% else %}
                        message-left
                    {% endif %}">
            <p>
                <strong>{{ message.sender.username }}</strong> <br>
                {{ message.content }} <br>
                ({{ message.timestamp }})
            </p>
        </div>
        {% empty %}
        <p>No messages to show.</p>
        {% endfor %}
    </div>

    <!-- <h1>Send Message</h1> -->
    <form method="POST">
        {% csrf_token %}
        <textarea name="content" rows="2"></textarea>
        <button type="submit">Send</button>
    </form>

    <button class="red" id="block-user-button">Block User</button>

    <dialog id="dialog-box">
        <p>Are you sure want to block the {{messaging_partner}}?</p>
        <div class="buttons-div">
            <button id="dialog-box-close">No</button>
            <a href="{% url 'messaging:block_user' messaging_partner_name=messaging_partner %}"><button id="block-user-confirm" class="red" type="submit">Yes</button></a>
        </div>
    </dialog>

    <script>
        const dialog = document.querySelector("dialog");
        const showButton = document.getElementById("block-user-button");
        const closeButton = document.getElementById("dialog-box-close");

        // "Show the dialog" button opens the dialog modally
        showButton.addEventListener("click", () => {
            dialog.showModal();
            dialog.classList.toggle("open");
        });

        // "Close" button closes the dialog
        closeButton.addEventListener("click", () => {
            dialog.classList.toggle("open");
            dialog.close();

        });
    </script>

</body>

</html>

messaging/templates/messaging/inbox.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <link rel="stylesheet" type="text/css" href="{% static 'messaging/inbox.css' %}">
</head>

<body>
    <div class="navbar">
        <h1>Messages</h1>
        <a href="{% url 'maps:map_view' %}" class="nav-link">Home</a>
        
    </div>

    <style>
        .message-left {
            text-align: left;
        }

        .message-right {
            text-align: right;
        }

        .conversation-tab {
            border: 1px solid black;
            margin: 10 auto;
            padding: auto;
        }
    </style>
</head>

<body>
    <!-- <a href="{% url 'maps:map_view' %}"><button>Home</button></a>

    <h1>Search Users</h1> -->

    <form method="get" action="">
        {{ form.as_p }}
        <button type="submit">Search</button>
    </form>

    <h1>Direct Messaging:</h1>

    {% for messaging_partner in start_conversations %}
    <a href="{% url 'messaging:direct_messaging' messaging_partner_name=messaging_partner %}">
        <div class="conversation-tab">
            <p>
                <strong>{{messaging_partner}}</strong> <br>
                Start Conversation
            </p>
        </div>
    </a>
    {% endfor %}

    {% for messaging_partner, conversation in conversation_history.items %}
    <a href="{% url 'messaging:direct_messaging' messaging_partner_name=messaging_partner %}">
        <div class="conversation-tab">
            <p>
                <strong>{{messaging_partner}}</strong> <br>
                {% if conversation.sender == user.username %}
                You: {{conversation.content}} <br>
                {% else %}
                Them: {{conversation.content}} <br>
                {% endif %}
                ({{ conversation.timestamp }})
            </p>
        </div>
    </a>
    {% endfor %}
</body>

</html>