app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("stations/", views.StationsView.as_view(), name="stations"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("save_favorite_route/", views.save_favorite_route, name="save_favorite_route"),
    path("stations/<int:station_id>/", views.station_detail, name="station_detail"),
    path("alerts/", views.alerts_view, name="alerts"),
]

notifications/urls.py
from django.urls import path
from . import views

app_name = "notifications"
urlpatterns = [
    path("inbox/", views.inbox, name="inbox"),
    path("get_notifications/", views.get_notifications, name="get_notifications"),
]

stepfreemta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("app/", include("app.urls", namespace="app")),
    path("admin/", admin.site.urls),
    path("admin_panel/", include("admin_panel.urls", namespace="admin_panel")),
    path("maps/", include("maps.urls", namespace="maps")),
    path("messaging/", include("messaging.urls", namespace="messaging")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
    path("reporting/", include("reporting.urls", namespace="reporting")),
    path("", lambda request: redirect("maps:map_view"), name="landing_page"),
]

notifications/models.py
from django.db import models


class Notifications(models.Model):
    active = models.BooleanField(default=True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from admin to all at {self.timestamp}"

notifications/views.py
from django.shortcuts import render
from .models import Notifications
from reporting.models import Report
from django.utils import timezone
from datetime import timedelta
from django.http import JsonResponse
from collections import defaultdict
from .dataclasses import ReportStatusFreqTable, StatusFreqTable


def inbox(request):
    notification_history = Notifications.objects.all().order_by("-timestamp")
    current_time = timezone.now()
    for record in notification_history:
        if current_time - record.timestamp >= timedelta(hours=24):
            record.active = False
            record.save()
    return render(request, "notifications/inbox.html", {})


def get_notifications(request):
    notification_history = Notifications.objects.all().order_by("-timestamp")
    current_time = timezone.now()
    relevant_notifications = []

    for record in notification_history:
        if current_time - record.timestamp >= timedelta(hours=24):
            break
        if record.active:
            relevant_notifications.append(
                {"content": record.content, "timestamp": record.timestamp}
            )

    reports = Report.objects.all().order_by("-timestamp")
    active_reports = defaultdict(
        lambda: ReportStatusFreqTable(
            active=StatusFreqTable(),
            broken=StatusFreqTable(),
            maintenance=StatusFreqTable(),
        )
    )
    for report in reports:
        if current_time - report.timestamp >= timedelta(hours=4):
            break

        report_key = (report.station, report.infrastructure)

        if current_time - report.timestamp < timedelta(hours=3):
            if report.status == "active":
                active_reports[report_key].active.count += 1
                active_reports[report_key].active.latest_timestamp = report.timestamp
            elif report.status == "broken":
                active_reports[report_key].broken.count += 1
                active_reports[report_key].broken.latest_timestamp = report.timestamp
            elif report.status == "maintenance":
                active_reports[report_key].maintenance.count += 1
                active_reports[report_key].maintenance.latest_timestamp = (
                    report.timestamp
                )

    for report_key in active_reports:
        count, timestamp, status = active_reports[report_key].get_top_status()
        if count >= 3:
            relevant_notifications.append(
                {
                    "content": f"{report_key[0]}'s {report_key[1]} is"
                    + f"{' in' if status == 'maintenance' else ''} {status}",
                    "timestamp": timestamp,
                }
            )

    return JsonResponse({"notifications": relevant_notifications})

notifications/templates/notifications/inbox.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'notifications/inbox.css' %}">

    <title>Notifications</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function fetchNotifications() {
            $.get("{% url 'notifications:get_notifications' %}", function (data) {
                let notificationsContainer = $('#notifications-container');
                notificationsContainer.empty();
                data.notifications.forEach(function (notification) {
                    notificationsContainer.append(
                        `<div>
                            <p>
                                ${notification.content} <br>
                                (${notification.timestamp})
                            </p>
                        </div>`
                    ); 
                });
                if(notificationsContainer.children().length === 0 ){
                    notificationsContainer.append(`<p>No notifications to show.</p>`);
                }
            });

            document.get
        }

        $(document).ready(function () {
            fetchNotifications();
            setInterval(fetchNotifications, 1000); // Fetch notifications every 1 seconds
        });
    </script>
</head>
<body>

    <div class = "navbar">
        <h1>Notifications</h1>
    <a href="{% url 'maps:map_view' %}"><button>Home</button></a>
    
</div>



    <div id="notifications-container">
    </div>
    
</body>


</html>